export const UPDATE_CLIENT_NAME = 'UPDATE_CLIENT_NAME';
export const UPDATE_CLIENT_PHONE = 'UPDATE_CLIENT_PHONE';
export const UPDATE_DATE = 'UPDATE_DATE';
export const CHOOSE_AVAILABLE_HOUR = 'CHOOSE_AVAILABLE_HOUR';
export const UPDATE_CLIENT_COMMENT = 'UPDATE_CLIENT_COMMENT';
